Add zsh function for cding to the root of the current git repository

diff --git a/shell/zsh/zshrc b/shell/zsh/zshrc
--- a/shell/zsh/zshrc
+++ b/shell/zsh/zshrc
@@ -133,6 +133,22 @@ function launch() {
     "$@" >/dev/null 2>&1 &
 }
 
+function cdr() {
+    if [[ $(git rev-parse --is-inside-work-tree 2> /dev/null) != 'true' ]]; then
+        echo "error: not in a git repository" 1>&2
+        return 1
+    fi
+
+    local relative_path="$1"
+    local root_path="$(git rev-parse --show-toplevel)"
+
+    if [[ -n "$relative_path" ]]; then
+        cd "$root_path/$relative_path"
+    else
+        cd "$root_path"
+    fi
+}
+
 ### KEY BINDINGS ###
 
 # Emacs keys pls 😈
